import { LexicalEditor } from 'lexical';
declare const useFormatBar: (editor: LexicalEditor) => {
    toolbarState: {
        bgColor: string;
        blockType: keyof typeof import('../../ToolbarContext').blockTypeToBlockName;
        canRedo: boolean;
        canUndo: boolean;
        codeLanguage: string;
        elementFormat: import('lexical').ElementFormatType;
        fontColor: string;
        fontFamily: string;
        fontSize: string;
        fontSizeInputValue: string;
        isBold: boolean;
        isCode: boolean;
        isHighlight: boolean;
        isImageCaption: boolean;
        isItalic: boolean;
        isLink: boolean;
        isRTL: boolean;
        isStrikethrough: boolean;
        isSubscript: boolean;
        isSuperscript: boolean;
        isUnderline: boolean;
        isLowercase: boolean;
        isUppercase: boolean;
        isCapitalize: boolean;
        rootType: "table" | "root";
    };
    onInsertLink: () => void;
    onFontColorSelect: (value: string, skipHistoryStack: boolean) => void;
    onBgColorSelect: (value: string, skipHistoryStack: boolean) => void;
    onPrint: () => void;
};
export { useFormatBar };
