export declare const menuButtonId: (menuId: string) => string;
export declare const menuListId: (menuId: string) => string;
export declare const menuItemId: (menuId: string, itemId: string) => string;
export declare const getMenuButton: (menuId: string) => HTMLButtonElement;
export declare const getMenuList: (menuId: string) => HTMLDivElement;
export declare const getMenuItem: (menuItemId: string) => HTMLElement | null;
export declare const firstMenuItemId: (menuElement: HTMLElement) => string;
export declare const lastMenuItemId: (menuElement: HTMLElement) => string;
export declare const nextMenuItemId: (menuElement: HTMLElement) => string;
export declare const previousMenuItemId: (menuElement: HTMLElement) => string;
export declare const dispatchSelectItemEvent: (menuElement: HTMLElement) => void;
export declare function menuItemByFirstCharacter(menuElement: HTMLElement, text: string): string;
