import { JSONSchema7, JSONSchema7Definition } from 'json-schema';
export declare function getProperty(field: string, jsonSchema?: JSONSchema7Definition): JSONSchema7 | undefined;
export declare function isJSONSchema(definition: JSONSchema7Definition | JSONSchema7Definition[] | null | undefined): definition is JSONSchema7;
export declare function isArrayValueEmptiable(schema: JSONSchema7): boolean;
export declare function isValueNullable(schema: JSONSchema7): boolean;
export declare function isInputRequired(schema: JSONSchema7): boolean;
export declare function isDate(schema: JSONSchema7): boolean;
export declare function isDateTime(schema: JSONSchema7): boolean;
export declare function isEnum(schema: JSONSchema7): boolean;
export declare function isOneOfEnum(schema: JSONSchema7): boolean;
export declare function isAutocomplete(schema: JSONSchema7): boolean;
export declare function schemaItemIsArray(field: string, jsonSchema?: JSONSchema7Definition | undefined): boolean;
