import { Meta } from '@storybook/react';
import { RadioGroup } from './RadioGroup';
declare const _default: Meta<typeof RadioGroup>;
export default _default;
export declare const Default: import('@storybook/core/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, {
    label: string;
    name: string;
    options: import('./RadioGroup').RadioOption[];
    className?: string;
    appearance?: import('..').Appearance;
    disabled?: boolean;
    required?: boolean;
    hint?: string;
    message?: string;
    value?: string;
    onChange?: (option: import('./RadioGroup').RadioOption) => void;
    defaultValue?: string;
}>;
export declare const Required: import('@storybook/core/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, {
    label: string;
    name: string;
    options: import('./RadioGroup').RadioOption[];
    className?: string;
    appearance?: import('..').Appearance;
    disabled?: boolean;
    required?: boolean;
    hint?: string;
    message?: string;
    value?: string;
    onChange?: (option: import('./RadioGroup').RadioOption) => void;
    defaultValue?: string;
}>;
