name: Storybook GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: Storybook GitHub Pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configura node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Installa dipendenze
        run: npm ci

      - name: Build Storybook
        run: npm run build-storybook

      - name: Upload pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-static

      - name: Deploy su GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
